const h = {
  children: {
    L: {
      children: {
        i: {
          children: {
            s: {
              children: {
                t: {
                  children: {
                    o: {
                      children: { n: { children: {}, endOfWord: true } },
                      endOfWord: false,
                    },
                  },
                  endOfWord: false,
                },
              },
              endOfWord: true,
            },
          },
          endOfWord: false,
        },
      },
      endOfWord: false,
    },
    F: {
      children: {
        e: {
          children: {
            r: {
              children: {
                m: {
                  children: { i: { children: {}, endOfWord: true } },
                  endOfWord: false,
                },
              },
              endOfWord: false,
            },
          },
          endOfWord: false,
        },
      },
      endOfWord: false,
    },
    A: {
      children: {
        k: {
          children: {
            i: {
              children: { l: { children: {}, endOfWord: true } },
              endOfWord: false,
            },
            a: {
              children: {
                s: {
                  children: { h: { children: {}, endOfWord: true } },
                  endOfWord: false,
                },
              },
              endOfWord: false,
            },
          },
          endOfWord: false,
        },
        r: {
          children: {
            a: {
              children: {
                v: {
                  children: {
                    i: {
                      children: {
                        n: {
                          children: { d: { children: {}, endOfWord: true } },
                          endOfWord: false,
                        },
                      },
                      endOfWord: false,
                    },
                  },
                  endOfWord: false,
                },
              },
              endOfWord: false,
            },
          },
          endOfWord: false,
        },
      },
      endOfWord: false,
    },
  },
  endOfWord: false,
};
